import type { Metadata } from "next";

import { Box, Stack } from "@mui/material";
import { HeaderLogin } from "@/components/layout/header/header-login";
import { Content } from "@/components/layout/content";
import { FooterLogin } from "@/components/layout/footer/footer-login";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderLogin />
      <Content>
        <Box
          display="flex"
          flexDirection="column"
          justifyContent="flex-start"
          flexGrow={1}
          p={4}
        >
          <Stack
            display="flex"
            alignItems="center"
            justifyContent="center"
            height="100%"
          >
            {children}
          </Stack>
        </Box>

        <FooterLogin />
      </Content>
    </>
  );
}
