import type { Metadata } from "next";

import { Stack } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Stack
      display="flex"
      alignItems="center"
      justifyContent="center"
      height="100%"
    >
      {children}
    </Stack>
  );
}
